name: Build APK on Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '21'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build Release APK
        run: ./gradlew assembleRelease

      - name: List build outputs (debug)
        run: find app/build/outputs -name "*.apk" -type f

      - name: Generate Amazon Access Token
        id: amazon-token
        env:
          AMAZON_CLIENT_ID: ${{ secrets.AMAZON_CLIENT_ID }}
          AMAZON_CLIENT_SECRET: ${{ secrets.AMAZON_CLIENT_SECRET }}
        run: |
          echo "Generating Amazon access token..."
          if [ -z "$AMAZON_CLIENT_ID" ] || [ -z "$AMAZON_CLIENT_SECRET" ]; then
            echo "Amazon credentials not configured, skipping..."
            exit 0
          fi
          
          TOKEN_RESPONSE=$(curl -s -X POST -H 'Content-Type: application/x-www-form-urlencoded' \
            -d "grant_type=client_credentials&client_id=${AMAZON_CLIENT_ID}&client_secret=${AMAZON_CLIENT_SECRET}&scope=appstore::apps:readwrite" \
            https://api.amazon.com/auth/O2/token)
          
          ACCESS_TOKEN=$(echo "$TOKEN_RESPONSE" | jq -r '.access_token // empty')
          
          if [ -n "$ACCESS_TOKEN" ]; then
            echo "✅ Successfully generated access token"
            echo "access_token=$ACCESS_TOKEN" >> $GITHUB_OUTPUT
          else
            echo "❌ Failed to generate access token"
            echo "Response: $TOKEN_RESPONSE"
          fi

      - name: Upload to Amazon Appstore
        if: steps.amazon-token.outputs.access_token != ''
        env:
          AMAZON_APP_ID: ${{ secrets.AMAZON_APP_ID }}
          AMAZON_ACCESS_TOKEN: ${{ steps.amazon-token.outputs.access_token }}
        run: |
          echo "Uploading APK to Amazon Appstore..."
          
          # Upload APK directly to Amazon Appstore
          UPLOAD_RESPONSE=$(curl -s -X POST "https://developer.amazon.com/api/appstore/v1/applications/${AMAZON_APP_ID}/apks" \
            -H "Authorization: Bearer ${AMAZON_ACCESS_TOKEN}" \
            -H "Content-Type: application/vnd.android.package-archive" \
            --data-binary @app/build/outputs/apk/release/app-release-unsigned.apk)
          
          if echo "$UPLOAD_RESPONSE" | grep -q "success\|uploaded\|200"; then
            echo "✅ APK successfully uploaded to Amazon Appstore"
          else
            echo "❌ Failed to upload APK to Amazon Appstore"
            echo "Response: $UPLOAD_RESPONSE"
          fi

      - name: Upload Release APK to GitHub
        uses: softprops/action-gh-release@v2
        with:
          files: app/build/outputs/apk/release/app-release-unsigned.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
